---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: destination
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-control-center:7.3.0
    init: confluentinc/confluent-init-container:2.5.0
  dataVolumeCapacity: 10Gi
  authentication:
    type: basic
    basic:
      secretRef: control-center-user
  configOverrides:
    server:
      - confluent.metrics.topic.max.message.bytes=8388608  
  dependencies:
    kafka:
      bootstrapEndpoint: pkc-l6wr6.europe-west2.gcp.confluent.cloud:9092
      authentication:
        type: plain
        jaasConfig:
          secretRef: dest-cloud-kafka-sasl
      tls:
        enabled: true
        ignoreTrustStoreConfig: true 
    schemaRegistry:
      url: https://psrc-y5q2k.europe-west3.gcp.confluent.cloud
      authentication:
        type: basic
        basic:
          secretRef: dest-cloud-sr-access
    connect:
    - name: connect-dev
      url:  http://replicator.destination.svc.cluster.local:8083