apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: production-storage-class
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
allowVolumeExpansion: false
volumeBindingMode: WaitForFirstConsumer