---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: confluent
spec:
  replicas: 1
  image:
    # if you're using a private registry, update these
    application: confluentinc/cp-server-connect:7.3.0
    init: confluentinc/confluent-init-container:2.5.0
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: myorg.com
      prefix: connect
  tls: 
    secretRef: connect-tls-cert
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      tls: 
        enabled: true
---
apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
  namespace: confluent
spec:
  replicas: 1
  image:
    # if you're using a private registry, update these
    application: confluentinc/cp-ksqldb-server:7.3.0
    init: confluentinc/confluent-init-container:2.5.0
  dataVolumeCapacity: 1Gi
  storageClass:
    name: production-storage-class
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: myorg.com
      prefix: ksqldb
  tls: 
    secretRef: ksqldb-tls-cert
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      tls: 
        enabled: true
---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 1
  image:
    # if you're using a private registry, update these
    application: confluentinc/cp-enterprise-control-center:7.3.0
    init: confluentinc/confluent-init-container:2.5.0
  dataVolumeCapacity: 1Gi
  storageClass:
    name: production-storage-class
  externalAccess:
    type: loadBalancer
    loadBalancer: 
      domain: myorg.com
      prefix: controlcenter
  tls:
    secretRef: c3-tls-cert
  dependencies:
    schemaRegistry:
      url: https://schemaregistry.confluent.svc.cluster.local:8081
      tls: 
        enabled: true
    ksqldb:
    - name: ksqldb
      url: https://ksqldb.confluent.svc.cluster.local:8088
      tls: 
        enabled: true
    connect:
    - name: connect
      url: https://connect.confluent.svc.cluster.local:8083
      tls: 
        enabled: true
---
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: confluent
spec:
  replicas: 1
  image:
    # if you're using a private registry, update these 
    application: confluentinc/cp-schema-registry:7.3.0
    init: confluentinc/confluent-init-container:2.5.0
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: myorg.com
      prefix: schemaregistry
  tls: 
    secretRef: sr-tls-cert
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      tls: 
        enabled: true
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafkarestproxy
  namespace: confluent
spec:
  replicas: 1
  image:
    # if you're using a private registry, update these  
    application: confluentinc/cp-kafka-rest:7.3.0
    init: confluentinc/confluent-init-container:2.5.0
  externalAccess:
    type: loadBalancer
    loadBalancer: 
      domain: myorg.com
      prefix: kafkarestproxy
  tls: 
    secretRef: krp-tls-cert
  dependencies:
    kafka:
      bootstrapEndpoint: kafka.confluent.svc.cluster.local:9071
      tls: 
        enabled: true
    schemaRegistry:
      url: https://schemaregistry.confluent.svc.cluster.local:8081
      tls: 
        enabled: true
