apiVersion: platform.confluent.io/v1beta1
# Confluent Replicator is built as a connector, and so we need to use the `Connect` CRD.
kind: Connect
metadata:
  name: replicator
  namespace: destination
spec:
  replicas: 1
  image:
    application: confluentinc/cp-enterprise-replicator:7.3.0
    init: confluentinc/confluent-init-container:2.5.0
  connectorTLSCerts:
    - secretRef: src-kafka-tls-cert
    - secretRef: src-sr-tls-cert
  podTemplate:
    envVars:
      - name: CLASSPATH
        value: /usr/share/java/kafka-connect-replicator/replicator-rest-extension-7.3.0.jar
  configOverrides:
    server:
      # To activate the monitoring extension, configure this property
      - rest.extension.classes=io.confluent.connect.replicator.monitoring.ReplicatorMonitoringExtension
      # This specifies that Replicator is the Connector configured
      - connector.class=io.confluent.connect.replicator.ReplicatorSourceConnector
  dependencies:
    kafka:
      bootstrapEndpoint: pkc-l6wr6.europe-west2.gcp.confluent.cloud:9092
      authentication:
        type: plain
        jaasConfig:
          secretRef: dest-cloud-kafka-sasl
      tls:
        enabled: true
        ignoreTrustStoreConfig: true 
    schemaRegistry:
      url: https://psrc-y5q2k.europe-west3.gcp.confluent.cloud
      authentication:
        type: basic
        basic:
          secretRef: dest-cloud-sr-access